---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: aqua-webhook
  name: aqua-webhook
  namespace: aqua
spec:
  ports:
    - name: aqua-webhook-ssl
      port: 8443
      protocol: TCP
      targetPort: 8445
    - name: aqua-webhook
      port: 8080
      protocol: TCP
      targetPort: 8082
  selector:
    app: aqua-webhook
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aqua-webhook
  name: aqua-webhook
  namespace: aqua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-webhook
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aqua-webhook
      name: aqua-webhook
      namespace: aqua
    spec:
      initContainers:
        - name: chmod-er
          image: busybox:latest
          command:
            - /bin/chown
            - -R
            - "1099"  # webhook UID
            - /server/database
          volumeMounts:
            - name: webhook-db
              mountPath: /server/database
      containers:
        - image: aquasec/postee:latest
          imagePullPolicy: Always
          name: aqua-webhook
          env:
            - name: AQUAALERT_CFG
              value: /policy/cfg.yaml/conf
            - name: AQUAALERT_DEBUG
              value: "not"
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8445
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /policy/cfg.yaml
            - name: webhook-db
              mountPath: /server/database
      volumes:
        - configMap:
            name: postee-config
            items:
              - key: cfg.yaml
                path: conf
          name: config-volume
        - name: webhook-db
          emptyDir: {}
          # In case to configure PVC
          # persistentVolumeClaim:
          #   claimName: postee-pvc
